export default [
	{ name: "defaultjs-html-components", branch: "master" },
	{ name: "defaultjs-template-language", branch: "master" },
	{ name: "defaultjs-expression-language", branch: "master" },
	{ name: "defaultjs-app-toolbox", branch: "master" },
	{ name: "defaultjs-html-form", branch: "master" },
	{ name: "defaultjs-html-renderer", branch: "main" },
	{ name: "defaultjs-html-pagination", branch: "main" },
	{ name: "defaultjs-html-typeahead", branch: "main" },
	{ name: "defaultjs-html-modal", branch: "main" },
	{ name: "defaultjs-html-jsondata", branch: "main" },
	{ name: "defaultjs-html-request", branch: "main" },
	{ name: "defaultjs-html-notification", branch: "main" },
	{ name: "defaultjs-html-dropdown", branch: "main" },
	{ name: "defaultjs-html-button", branch: "main" },
	{ name: "defaultjs-extdom", branch: "master" },
	{ name: "defaultjs-fetch-extentions", branch: "main" },
	{ name: "defaultjs-httpinterceptor", branch: "master" },
	{ name: "defaultjs-dynamic-requester", branch: "master" },
	{ name: "defaultjs-logging", branch: "master" },
	{ name: "defaultjs-common-utils", branch: "master" },
];
